name: shelf_packages_handler
version: 2.0.1

description: A shelf handler for serving a `packages/` directory.
repository: https://github.com/dart-lang/shelf_packages_handler

environment:
  sdk: '>=2.8.0 <3.0.0'

dependencies:
  path: ^1.0.0
  shelf: '>=0.7.0 <2.0.0'
  shelf_static: ^0.2.0

dev_dependencies:
  pedantic: ^1.9.0
  test: '>=1.0.0 <2.0.0'
