name: shelf_test_handler
version: 1.0.0-dev
description: A Shelf handler that makes it easy to test HTTP interactions.
author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/shelf_test_handler

environment:
  sdk: '>=1.8.0 <2.0.0'

dependencies:
  shelf: "^0.6.0"
  test: "^0.12.0"
