name: shelf_static
version: 0.2.2-dev
author: Kevin Moore <github@j832.com>
description: Static file server support for Shelf
homepage: https://github.com/kevmoo/shelf_static.dart
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  http_parser: '>=0.0.2+2 <0.1.0'
  mime: '>=0.9.0 <0.10.0'
  shelf: '>=0.5.3 <0.6.0'
dev_dependencies:
  args: '>=0.12.0 <0.13.0'
  hop: '>=0.30.4 <0.32.0'
  hop_unittest: '>=0.1.0 <0.2.0'
  path: '>=1.1.0 <2.0.0'
  scheduled_test: '>=0.11.0 <0.12.0'
