name: shelf_proxy
version: 0.0.2-dev
author: Kevin Moore <github@j832.com>
description: Shelf handlers to proxy requests to other HTTP servers
homepage: https://github.com/kevmoo/shelf_proxy
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  http_parser: '>=0.0.2+2 <0.1.0'
  mime: '>=0.9.0 <0.10.0'
  shelf: '>=0.5.3 <0.6.0'
dev_dependencies:
  hop: '>=0.30.4 <0.32.0'
  hop_unittest: '>=0.1.0 <0.2.0'
  path: '>=1.1.0 <2.0.0'
  scheduled_test: '>=0.11.0 <0.12.0'
  shelf_static: any
