name: shelf_static
version: 0.0.0-dev
description: Static file server support for Shelf
dependencies:
  shelf: '>=0.5.0 <0.6.0'
dev_dependencies:
  hop: '>=0.30.2 <0.31.0'
  scheduled_test: '>=0.11.0 <0.12.0'
